version: "3"

services:
  builder:
    build:
      context: builder
    image: enumivo/builder

  enunoded:
    build:
      context: .
    image: enumivo/enumivo
    command: /opt/enumivo/bin/nodeosd.sh --data-dir /opt/enumivo/bin/data-dir
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - enunode-data-volume:/opt/enumivo/bin/data-dir

  keosd:
    image: enumivo/enumivo
    command: /opt/enumivo/bin/keosd --wallet-dir /opt/enumivo/bin/data-dir
    hostname: keosd
    links:
      - enunoded
    volumes:
      - keosd-data-volume:/opt/enumivo/bin/data-dir

volumes:
  enunode-data-volume:
    external: true
  keosd-data-volume:
    external: true
