version: "3"

services:
  builder:
    build:
      context: builder
    image: enumivo/builder

  nodeosd:
    build:
      context: .
    image: enumivo/eos
    command: /opt/enumivo/bin/nodeosd.sh
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/enumivo/bin/data-dir

  keosd:
    image: enumivo/eos
    command: /opt/enumivo/bin/keosd
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/enumivo/bin/data-dir

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
